# Generated by Django 5.0.7 on 2024-07-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
