# Generated by Django 5.0.7 on 2024-07-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.IntegerField(choices=[(1, 'FEATURES'), (2, 'BUG'), (3, 'TEST'), (4, 'QA'), (5, 'DOCUMENTATION'), (6, 'OTHER')]),
        ),
    ]
